config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :questions
  resources :answers
  resources :users
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
  end

  def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
  end

  helper_method :current_user_session, :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    def new
        @user_session = UserSession.new
    end

    def create
        @user_session = UserSession.new(user_session_params)
        if @user_session.save
            flash[:success] = "Welcome back!"
            redirect_to root_path
        else
            render :new
        end
    end

    def destroy
        current_user_session.destroy
        flash[:success] = "Bye"
        redirect_to root_path
    end

    private

    def user_session_params
        params.require(:user_session).permit(:login, :password, :remember_me)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(users_params)
        if @user.save
            redirect_to root_path
        else
            render :new
        end
    end

    def destroy
        current_user_session.destroy
        redirect_to root_path
    end

    private

    def users_params
        params.require(:user).permit(:login, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  private
  def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
  end

  def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
  end

  helper_method :current_user_session, :current_user
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zheye</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-warning errors">
        <div class="panel-heading">
            <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
        </div>

        <ul class="panel-body">
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
    <%= render 'shared/errors', object: @user_session %>

    <div class="form-group">
        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :remember_me %>
        <%= f.check_box :remember_me %>
    </div>

    <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>

    <%= render 'shared/errors', object: @user %>
    <div class="form-group">
        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Zheye</h1>
<p>Welcome to Zheye!</p>
<ul class="nav navbar-nav pull-right">
    <% if current_user %>
        <li><span><%= current_user.login %></span></li>
        <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
    <% else %>
        <li><%= link_to 'Sign In', sign_in_path %></li>
    <% end %>
</ul>
<p>Sign up to get started.</p>
<p>
    <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
        Sign Up &raquo;
    <% end %>
</p>